arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-class: L10n
untranslated-messages-file: lib/l10n/untranslated_messages.json
preferred-supported-locales:
  - en
  - th
  - vi
  - id
  - zh
  - ja
  - ko
  - es
  - fr
  - de
  - pt
  - hi
