// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW5_bd5s-JDBjZlPgnMyzjZKjvVKtnjWo',
    appId: '1:65396857547:web:placeholder',
    messagingSenderId: '65396857547',
    projectId: 'miro-d6856',
    authDomain: 'miro-d6856.firebaseapp.com',
    storageBucket: 'miro-d6856.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW5_bd5s-JDBjZlPgnMyzjZKjvVKtnjWo',
    appId: '1:65396857547:android:d89fc49b7dcd4e58a4d94e',
    messagingSenderId: '65396857547',
    projectId: 'miro-d6856',
    storageBucket: 'miro-d6856.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-cwx5eNc1B3KHVNLeOoMRfwqLbxFN1LA',
    appId: '1:65396857547:ios:cf4497c3d0968344a4d94e',
    messagingSenderId: '65396857547',
    projectId: 'miro-d6856',
    storageBucket: 'miro-d6856.firebasestorage.app',
    iosBundleId: 'com.tanabun.miroHybrid',
  );
}
