import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service — MiRO',
  description:
    'MiRO terms of service. Read the terms and conditions for using the MiRO app.',
};

export default function TermsPage() {
  return (
    <div className="pt-24 pb-16">
      <section className="hero-gradient pb-12 pt-12">
        <div className="mx-auto max-w-4xl px-4 text-center sm:px-6 lg:px-8">
          <h1 className="text-4xl font-bold tracking-tight sm:text-5xl">
            Terms of Service
          </h1>
          <p className="mt-4 text-gray-400">Last updated: March 1, 2026</p>
        </div>
      </section>

      <article className="mx-auto max-w-4xl px-4 py-12 sm:px-6 lg:px-8">
        <div className="prose prose-invert prose-gray max-w-none space-y-8 text-gray-300 [&_h2]:text-xl [&_h2]:font-bold [&_h2]:text-white [&_h2]:mt-10 [&_h2]:mb-4 [&_h3]:text-lg [&_h3]:font-semibold [&_h3]:text-white [&_h3]:mt-6 [&_h3]:mb-3 [&_p]:leading-relaxed [&_ul]:space-y-2 [&_li]:text-gray-400">
          <section>
            <h2>1. Acceptance of Terms</h2>
            <p>
              By downloading, installing, or using MiRO (&quot;My Intake Record
              Oracle&quot;), you agree to be bound by these Terms of Service. If you
              do not agree, please do not use the app.
            </p>
          </section>

          <section>
            <h2>2. Description of Service</h2>
            <p>
              MiRO is a mobile application that helps users track food intake
              and nutrition using AI-powered analysis. The app provides:
            </p>
            <ul>
              <li>AI-powered food photo analysis and nutrition estimation</li>
              <li>Manual food logging and tracking</li>
              <li>Personal meal database that grows with usage</li>
              <li>Chat-based food logging with natural language</li>
              <li>Integration with device Health systems</li>
              <li>Nutrition reports and insights</li>
            </ul>
          </section>

          <section>
            <h2>3. No Account Required</h2>
            <p>
              MiRO does not require you to create an account, sign up, or
              provide any personal information to use the app. Your data is
              stored locally on your device, with compact backups synced
              automatically to our servers during daily Energy claims to enable
              cross-device restoration.
            </p>
          </section>

          <section>
            <h2>4. Energy System &amp; In-App Purchases</h2>
            <h3>4.1 Energy Tokens</h3>
            <p>
              Energy is MiRO&apos;s in-app currency used for AI-powered features.
              Energy tokens are consumable digital goods.
            </p>
            <ul>
              <li>Energy tokens are non-refundable once used</li>
              <li>Purchased Energy tokens do not expire</li>
              <li>
                Energy is tied to your device; transferring Energy requires the
                in-app transfer feature
              </li>
              <li>
                Free Energy received through promotions, streaks, or referrals
                is subject to the same terms
              </li>
            </ul>

            <h3>4.2 Energy Pass Subscription</h3>
            <p>
              The Energy Pass is an optional monthly subscription that provides
              unlimited AI analysis and additional benefits. Subscriptions are
              managed through Google Play or the Apple App Store:
            </p>
            <ul>
              <li>
                Subscriptions auto-renew unless cancelled at least 24 hours
                before the end of the current billing period
              </li>
              <li>
                You can cancel anytime through your device&apos;s subscription
                settings
              </li>
              <li>
                No refunds for partial billing periods after cancellation
              </li>
              <li>
                Subscription benefits end at the conclusion of the paid billing
                period
              </li>
            </ul>

            <h3>4.3 Pricing</h3>
            <p>
              Prices are displayed in your local currency and may vary by
              region. We reserve the right to change pricing at any time.
              Existing purchased Energy tokens are not affected by price changes.
            </p>
          </section>

          <section>
            <h2>5. AI Analysis Disclaimer</h2>
            <p>
              MiRO&apos;s AI-powered food analysis provides <strong className="text-white">estimates only</strong>.
              Nutritional values generated by AI should be considered
              approximations and not precise medical data.
            </p>
            <ul>
              <li>
                AI analysis accuracy depends on photo quality, food
                presentation, and cuisine complexity
              </li>
              <li>
                Users should not rely solely on MiRO for medical dietary
                decisions
              </li>
              <li>
                Consult a healthcare professional or registered dietitian for
                medical nutrition advice
              </li>
              <li>
                MiRO is not a medical device and is not intended to diagnose,
                treat, cure, or prevent any disease
              </li>
            </ul>
          </section>

          <section>
            <h2>6. User Responsibilities</h2>
            <ul>
              <li>
                You are responsible for the accuracy of manually entered food
                data
              </li>
              <li>
                Food history is automatically backed up during daily Energy
                claims; you are responsible for keeping your Recovery Key secure
              </li>
              <li>
                You agree not to misuse the AI features (e.g., submitting
                inappropriate content for analysis)
              </li>
              <li>
                You agree not to attempt to reverse-engineer, decompile, or
                disassemble the app
              </li>
              <li>
                You agree not to exploit bugs or vulnerabilities in the Energy
                system
              </li>
            </ul>
          </section>

          <section>
            <h2>6.1 Cloud Backup &amp; Recovery Key</h2>
            <p>
              MiRO automatically backs up your food history (nutrition text data
              and small thumbnail images) during daily Energy claims.
            </p>
            <ul>
              <li>
                A Recovery Key (MIRO-XXXX-XXXX) is generated for your account,
                viewable in Profile → Account
              </li>
              <li>
                Use your Recovery Key to restore your account on a new device
              </li>
              <li>
                Redeeming a Recovery Key transfers Energy balance, food history,
                and generates a new key for the new device
              </li>
              <li>
                Recovery Keys are single-use — once redeemed, the old key is
                invalidated
              </li>
              <li>
                Keep your Recovery Key secure — anyone with it can claim your
                account and Energy
              </li>
              <li>
                You can regenerate your Recovery Key at any time (this
                invalidates the previous key)
              </li>
              <li>
                Full-resolution food photos are NOT included in cloud backups —
                only small thumbnails (~40-80 KB)
              </li>
            </ul>
          </section>

          <section>
            <h2>7. Intellectual Property</h2>
            <p>
              MiRO, including its design, code, AI models, and content, is the
              intellectual property of TNB Group. You are granted a limited,
              non-exclusive, non-transferable license to use the app for
              personal, non-commercial purposes.
            </p>
          </section>

          <section>
            <h2>8. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, TNB Group shall not be
              liable for:
            </p>
            <ul>
              <li>
                Inaccuracies in AI-generated nutritional information
              </li>
              <li>Loss of data stored locally on your device</li>
              <li>
                Health decisions made based on information provided by the app
              </li>
              <li>
                Interruption or unavailability of AI services due to third-party
                dependencies
              </li>
              <li>
                Any indirect, incidental, or consequential damages arising from
                use of the app
              </li>
            </ul>
          </section>

          <section>
            <h2>9. Referral Program</h2>
            <p>
              MiRO&apos;s referral program rewards users for inviting friends.
              Referral rewards are subject to verification (the referred user
              must complete qualifying actions). We reserve the right to
              withhold rewards in cases of suspected fraud or abuse.
            </p>
          </section>

          <section>
            <h2>10. Termination</h2>
            <p>
              You may stop using MiRO at any time by uninstalling the app. We
              reserve the right to suspend or terminate access to cloud-based
              features (AI analysis, Energy system) if these terms are violated.
              Locally stored data remains on your device regardless. Cloud-synced
              food history and Energy balance are preserved on our servers and
              can be restored using your Recovery Key.
            </p>
          </section>

          <section>
            <h2>11. Changes to Terms</h2>
            <p>
              We may update these Terms of Service from time to time. Continued
              use of MiRO after changes constitutes acceptance of the updated
              terms. Significant changes will be communicated through the app or
              on this page.
            </p>
          </section>

          <section>
            <h2>12. Governing Law</h2>
            <p>
              These Terms are governed by the laws of Thailand. Any disputes
              shall be resolved in the courts of Thailand.
            </p>
          </section>

          <section>
            <h2>13. Contact</h2>
            <p>
              For questions about these Terms of Service, contact us at:
            </p>
            <ul>
              <li>
                Email:{' '}
                <a
                  href="mailto:support@tnbgrp.com"
                  className="text-brand-400 underline"
                >
                  support@tnbgrp.com
                </a>
              </li>
              <li>Website: www.tnbgrp.com</li>
              <li>Publisher: TNB Group</li>
            </ul>
          </section>
        </div>
      </article>
    </div>
  );
}
